### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'constants.bin'

### ISSUE THREAD

**Issue by krivellari** [karayaman/lichess-with-a-real-board#6]
I keep getting the following error:

Traceback (most recent call last):
File "main.py", line 59, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'constants.bin'
[8536] Failed to execute script 'main' due to unhandled exception!
Game finished.

How do I solve this?

**Comment by karayaman** [comment]
You are getting the error, because it is not saving the calibration result. Make sure to press the key "q" after it detects the chess board.
